### ISSUE TITLE
Introduce error type of crate itself

### ISSUE THREAD

**Issue by peterjoel** [rdelfin/async-zmq#1]
In README, it states:

>  Another common issue when people adopting a library is to deal with its error handling flow. To prevent introducing more overhead, async_zmq uses the exact same Result/Error type in zmq crate and re-export them.

I believe this is a mistake. There is a very standard way of modeling errors in Rust, which is quite different from the `zmq::Error` type. It is more important to be consistent with other crates in the Rust ecosystem than to mirror the underlying C types.

In my experience of working with the `zmq` crate, it is very hard to know which of the 28 error variants are possible for any given operation. Most are generally not applicable, or are applicable to certain operations but not others. Instead of having to refer to the ZMQ C documention, I would much rather lean on the Rust type system to tell me  exactly which errors I need to handle in a particular case.

A good example of this done well is the design of error handling for channels in `std`, or `crossbeam_channel`. Each operation has its own error type, which represents exactly the errors that could occur.

**Comment by peterjoel** [comment]
On another note, this looks like great work. I was very happy to find it :)

**Comment by wusyong** [comment]
That's fair point. Allow me to rename the issue. I will look into this, or anyone who is interested is also welcome to open a PR :)
