### ISSUE TITLE
poll_event() never returns Pending state, causing the examples to fail

### ISSUE THREAD

**Issue by dotdash** [rdelfin/async-zmq#12]
Since the introduction of the runtime agnostic code (I guess!) the poll_event() function no longer returns Poll::Pending, only Poll::Ready, possibly with a `Err(Error::EAGAIN)` value. This makes the examples fail with 

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unexpected(Resource temporarily unavailable)', examples/reply.rs:12:19

**Comment by peterjoel** [comment]
Yep, it shouldn't do that.

**Comment by wusyong** [comment]
Sorry for the late update. I have update how event is polled. Now it will return `Poll::Pending` if socket doesn't contain the event we want.
Thanks for reporting the issue!
