### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rdelfin** [rdelfin/async-zmq#15]
Is there a new release planned for this crate? I was planning on using the vendored zmq feature but I see the latest release doesn't support it. When is a new release expected?

**Comment by daniel-brenot-apcapital** [comment]
Bumping this to ask if you are willing to introduce any maintainers? I need this for work and at the moment my solution will be to keep a fork maintained. 

Thanks for all your hard work.

**Comment by rdelfin** [comment]
@wusyong just wanted to bump this again as this crate is extremely valuable for some work I'm doing. I'd be happy to join Daniel in supporting this. Thoughts?

**Comment by wusyong** [comment]
@rdelfin Hey sorry for not replying such long. I didn't aware this crate is being used.
I no longer maintained it unfortunately. But I can move the ownership of it to anyone who want to take the responsibility.
Do you wish to take?

**Comment by rdelfin** [comment]
@wusyong I'd be more than happy to! I've started a fork for it and I'd love to contribute further to this

**Comment by wusyong** [comment]
@rdelfin Can you give me your username on crates.io? I'll transfer it too at the same time.

Edit: You probably want to remove the fork. I recalled Github can't transfer repo if there's already a fork.

**Comment by rdelfin** [comment]
@wusyong you can find me with the email "me@rdelfin.com", I've linked it to my github so the user should be rdelfin, and display name is "Ricardo Delfin". I've deleted the fork

**Comment by wusyong** [comment]
Both requests were sent. Let me know if there's any issue.

**Comment by rdelfin** [comment]
I'm closing this as we've had a release since
