### ISSUE TITLE
The type `struct Reply` is not Send?

### ISSUE THREAD

**Issue by wongsingfo** [rdelfin/async-zmq#20]
I encountered an issue with the struct Reply when trying to use it in a concurrent context. I want to know why it is not Send and if there is a way to make it work. Thank you for the help.

Here is the code I am trying to run, the `src/main.rs` file:

```rs
use async_zmq;
use futures_util::stream::StreamExt;
use tokio;

async fn foo() {
    let mut socket = async_zmq::reply("tcp://localhost:1234")
        .unwrap()
        .bind()
        .unwrap();

    while let Some(Ok(msg)) = socket.next().await {
        let f = socket.send(msg);
        f.await.unwrap();  // <-- Commenting this line out makes the code compile.
    }

}

#[tokio::main]
async fn main() {
    // The spawn(x) requires x to be Send, and the compiler complains about the foo() function not
    // being Send. The compiler gives a hint that "within `Reply<std::vec::IntoIter<Message>,
    // Message>`, the trait `Sync` is not implemented for `*mut c_void`". I don't understand where
    // does the `*mut c_void` come from.
    let handle = tokio::spawn(foo());

    // tokio::spawn(bar());
    // tokio::spawn(other_tasks());

    handle.await.unwrap();
}
```

And the `Cargo.toml` file:

```
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# common utils
futures = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = ["full"] }
async_zmq = "0.3.3"
```

**Comment by jobfeikens** [comment]
> Don't share ZeroMQ sockets between threads. ZeroMQ sockets are not threadsafe. Technically it's possible to migrate a socket from one thread to another but it demands skill. The only place where it's remotely sane to share sockets between threads are in language bindings that need to do magic like garbage collection on sockets.

https://zguide.zeromq.org/docs/chapter2/

**Comment by rdelfin** [comment]
I'll close due to @jobfeikens comment, but @wongsingfo if you have a follow up on this feel free to reopen
