### ISSUE TITLE
Please update to new release of zmq

### ISSUE THREAD

**Issue by chikko80** [rdelfin/async-zmq#21]
Please update to latest zmq version 0.10.0

**Comment by rdelfin** [comment]
Hi @chikko80, thanks for the ping and sorry for the delay! Let me look into how difficult it would be to update

**Comment by RockyGitHub** [comment]
Hello!  I'm also hoping this can be updated to the latest zmq :)

**Comment by guenhter** [comment]
Also looking forward for this. @rdelfin Did you had the chance to have a look?

**Comment by rdelfin** [comment]
I have not, thanks for putting a PR out. I'll get things prepared and do a new release this weekend

**Comment by rdelfin** [comment]
I've now made a release for v0.4.0 using zmq version 0.10.0. Feel free to update your local versions

**Comment by thierry-tct** [comment]
Thank you for that. I was also waiting for the upgrade.
