### ISSUE TITLE
Support re-use of Context

### ISSUE THREAD

**Issue by peterjoel** [rdelfin/async-zmq#3]
In general, only one context is needed in an application. For inproc sockets, the same context _must_ be used. It should be possible to provide the context when creating a socket.

**Comment by wusyong** [comment]
Added some methods to support this in commit [`5e687da`](https://github.com/wusyong/async-zmq/commit/5e687da22d74c38aa4da6bb52bab8987fe024549). I will resolve this after updating README and maybe some more tests.
